### ISSUE TITLE
[UI] Mobile Friendly

### ISSUE THREAD

**Issue by AnthonyMadia** [Unirep/explorer#28]
Add support for a mobile friendly UI.

**Comment by ChialiT** [comment]
@CJ-Rose can u estimate the effort here, if its pretty huge we can do in V1.0 release instead of v0.1

**Comment by CJ-Rose** [comment]
I don't think this is something I can accomplish in the next few days for a timely release (along with other updates currently coming up from staging review). I think a decent mobile UI will require significant changes to the layout; I can't just make everything smaller to fit.. will need to change the composition of the elements.

That being said, if this is something the team feels is high priority for this release then I can try to make some simple improvements (like just make everything smaller ;) -- it wouldn't be ideal but could at least be useable.

**Comment by ChialiT** [comment]
I think we can do it for V1.0 release instead. 
There will be few design changes when we do V1.0, its better to do those UI at same time I think.
