### ISSUE TITLE
[Features] Add etherscan link to epoch key

### ISSUE THREAD

**Issue by ChialiT** [Unirep/explorer#30]
![image.png](https://images.zenhubusercontent.com/632a7d53a185f62cf181667a/735519d0-d2ce-492b-b93d-cee313a62580)

Can add an arrow in the table row

**Comment by CJ-Rose** [comment]
Do you mean to add the arrow next to the epoch key in the box on the left? Because I think adding it to the row in the table of attestations would imply a link to the transaction, not the epoch key.

**Comment by ChialiT** [comment]
Mmm, got your point.
the "epoch status" is talking about the status, and we want to link to etherscan in order to see if its complete.

@vivianjeng what do you think?
do you think it makes more sense to put it at left side, where the epoch key info box, or
at right side in the row, where we talk about epoch status?

**Comment by CJ-Rose** [comment]
also bc we are looking here at a single epoch, if the arrow is in the attestation table then each row will have a link to the same place. So I think the 'Epoch status' stat needs to be moved from the row into the box on the left as well.

**Comment by ChialiT** [comment]
revisiting,

<img width="2008" alt="image" src="https://github.com/Unirep/explorer/assets/16527634/9169d0f1-0af7-4665-b28f-83cef96f42ea">

**Comment by kittybest** [comment]
already merged to main.
