### ISSUE TITLE
[UI] support different chains

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/explorer#39]
we deploy unirep in different chains
- [Goerli Testnet](https://goerli.etherscan.io/address/0xCa61bFcA0107c5952f8bf59f4D510d111cbcE146)
- [arbitrum goerli](https://goerli.arbiscan.io/address/0xCa61bFcA0107c5952f8bf59f4D510d111cbcE146)
- [PolygonScan Testnet](https://mumbai.polygonscan.com/address/0xCa61bFcA0107c5952f8bf59f4D510d111cbcE146)
- [Sepolia Testnet](https://sepolia.etherscan.io/address/0xCa61bFcA0107c5952f8bf59f4D510d111cbcE146)

we can support a selector to select between different chains
and backend should sync all the data in different chains

**Comment by kittybest** [comment]
already merged to main.
