### ISSUE TITLE
[Feature] Attester info description

### ISSUE THREAD

**Issue by 0xWOLAND** [Unirep/explorer#40]
- give ECDSA signature using attester deployer key
- sign text description to be shown to attester

For the initial version, we will sign a short text description about an attester site. This issue will entail  [ERC-1271](https://eips.ethereum.org/EIPS/eip-1271) which describes how a smart contract can verify if a signature can sign on its behalf. However, the attester should implement this EIP, but we should check if it has been implemented or not using [ERC-165](https://eips.ethereum.org/EIPS/eip-165). We then verify the signed message against the smart contract and update explorer.

In a follow-up issue, we can create a util that parses a stringified JSON literal.

**Comment by ChialiT** [comment]
related to: https://github.com/Unirep/explorer/issues/38
