### ISSUE TITLE
[Frontend] favicon not found

### ISSUE THREAD

**Issue by kittybest** [Unirep/explorer#76]

**Comment by kittybest** [comment]
**UPDATED**
actually `favicon.ico` is loaded, but Chrome won't display favicon if it's running locally, so we could close this issue.

**Comment by vivianjeng** [comment]
we can still use this line in webpack
https://github.com/Unirep/explorer/blob/852395c89fe5052afb592d0d397dda8dc29d7d43/packages/frontend/webpack.config.js#L76
So it will copy the `favicon.ico` to the `build/` directory

(I reverted the vercel commitment in main and create another PR in https://github.com/Unirep/explorer/pull/77
both add this line (but not yet merge to main)
